function [g, u, m, modecolor, cmodecolor] = eegplot_create_ui(figh, g, data, EEG, ax0, ax1, colors)
% eegplot_create_ui() - Create all UI controls and menus for eegplot_adv
%
% Usage:
%   [g, u, m, modecolor, cmodecolor] = eegplot_create_ui(figh, g, data, EEG, ax0, ax1, colors)
%
% Inputs:
%   figh   - figure handle
%   g      - eegplot_adv userdata struct
%   data   - EEG data matrix
%   EEG    - EEG struct
%   ax0    - background axes handle
%   ax1    - EEG data axes handle
%   colors - struct with color/style defaults:
%            DEFAULT_FIG_COLOR, DEFAULT_PLOT_BACKGROUND, DEFAULT_PLOT_INTERP,
%            DEFAULT_ON_COLOR, DEFAULT_OFF_COLOR, DEFAULT_SPECIAL_COLOR,
%            DEFAULT_SPECIAL_TEXT, DEFAULT_AXIS_COLOR, BUTTON_COLOR,
%            DEFAULT_AXES_POSITION, DEFAULT_GRID_STYLE
%
% Outputs:
%   g          - updated userdata struct
%   u          - array of uicontrol handles
%   m          - array of uimenu handles
%   modecolor  - color for the Display mode button
%   cmodecolor - color for the SWITCH (ICA/EEG) button

% Unpack color variables from struct
DEFAULT_FIG_COLOR       = colors.DEFAULT_FIG_COLOR;
DEFAULT_PLOT_BACKGROUND = colors.DEFAULT_PLOT_BACKGROUND;
DEFAULT_PLOT_INTERP     = colors.DEFAULT_PLOT_INTERP;
DEFAULT_ON_COLOR        = colors.DEFAULT_ON_COLOR;
DEFAULT_OFF_COLOR       = colors.DEFAULT_OFF_COLOR;
DEFAULT_SPECIAL_COLOR   = colors.DEFAULT_SPECIAL_COLOR;
DEFAULT_SPECIAL_TEXT    = colors.DEFAULT_SPECIAL_TEXT;
DEFAULT_AXIS_COLOR      = colors.DEFAULT_AXIS_COLOR;
BUTTON_COLOR            = colors.BUTTON_COLOR;
DEFAULT_AXES_POSITION   = colors.DEFAULT_AXES_POSITION;
DEFAULT_GRID_STYLE      = colors.DEFAULT_GRID_STYLE;

  %% Set up uicontrols
  % %%%%%%%%%%%%%%%%%%%%%%%%%
  
  div = 0.02 + DEFAULT_AXES_POSITION(2) + DEFAULT_AXES_POSITION(3); % this contains the right end of plot
  max_wi = 1 - div - .005;
  half_wi = max_wi/2;
  un = (max_wi/16);
  heights =      [.02, .015,.03, .04];
  bottoms =      [div,div+half_wi,div+un*2,div+un*5,div+un*11,div+un*14,div+un*4,div+un*3/2];
  widths =       [max_wi/2,max_wi,max_wi/8,3*(max_wi/16),max_wi/4,];
  %heights =      [.02, .015,.03, .04];
  %bottoms =      [.915,.955,.925,.935,.94,.97,0.985,.922];
  %widths =       [.04,.08,.01,.015,.20];

  r = -.01;

% positions of buttons
%                  bottom  left    width    heigth
% numbers go from 1 and end at 47 (need to be reorganized)
  posbut(22,:) = [ bottoms(1)    0.98+r    widths(1)    heights(1) ]; % stack channels(same offset)  
  posbut(21,:) = [ bottoms(1)    0.96+r    widths(1)    heights(1) ]; % normalize
  posbut(17,:) = [ bottoms(1)    0.94+r    widths(1)    heights(1) ]; % events types
  
  posbut(14,:) = [ bottoms(1)    0.90+r    widths(1)    heights(1) ]; % elec tag
  posbut(7,:) =  [ bottoms(1)    0.885+r    widths(1)    heights(1) ]; % elec
  
  posbut(16,:) = [ bottoms(1)    0.86+r    widths(1)    heights(1) ]; % value tag
  posbut(9,:) =  [ bottoms(1)    0.845+r    widths(1)    heights(1) ]; % value
  
  posbut(15,:) = [ bottoms(1)    0.82+r    widths(1)    heights(1) ]; % g.time tag
  posbut(8,:) =  [ bottoms(1)    0.805+r    widths(1)    heights(1) ]; % g.time   

%% New file description texts about the file

  posbut(60,:) = [ bottoms(2)    0.98+r    widths(1)    heights(1) ]; % Number of Channels tag
  posbut(61,:) = [ bottoms(2)    0.965+r    widths(1)    heights(1) ]; % Number of Channels
  
  posbut(62,:) = [ bottoms(2)    0.94+r    widths(1)    heights(1) ]; % Frames/Sampling Rate tag
  posbut(63,:) = [ bottoms(2)    0.925+r    widths(1)    heights(1) ]; % Frames/Sampling Rate

  posbut(64,:) = [ bottoms(2)    0.90+r    widths(1)    heights(1) ]; % Epochs/Events tag
  posbut(65,:) = [ bottoms(2)    0.885+r    widths(1)    heights(1) ]; % Epochs/Events

  posbut(66,:) = [ bottoms(2)    0.86+r    widths(1)    heights(1) ]; % Epoch Start/End tag
  posbut(67,:) = [ bottoms(2)    0.845+r    widths(1)    heights(1) ]; % Epoch Start/End

  posbut(68,:) = [ bottoms(2)    0.82+r    widths(1)    heights(1) ]; %  ICA weights/rank tag
  posbut(69,:) = [ bottoms(2)    0.805+r    widths(1)    heights(1) ]; %  ICA weights/rank
    

  %% New Buttons to navigate identified marks

  posbut(70,:) = [ bottoms(1)    0.48+r    widths(3)    heights(1) ]; %  ICA weights/rank tag
  posbut(71,:) = [ bottoms(6)    0.48+r    widths(3)    heights(1) ]; %  ICA weights/rank

%% Epoch editbox, arrows, scale size, number of channels display

  posbut(5,:) =  [ bottoms(1)    0.78+r    widths(2)    heights(1) ]; % Eposition .52
  posbut(46,:) = [ bottoms(1)    0.76+r    widths(3)        heights(1) ]; % |<<  % NEW UGO
  posbut(1,:) =  [ bottoms(3)    0.76+r    widths(4)        heights(1) ]; % <<  
  posbut(2,:) =  [ bottoms(4)    0.76+r    widths(4)        heights(1) ]; % <  
  posbut(3,:) =  [ bottoms(2)    0.76+r    widths(4)        heights(1) ]; % >
  posbut(4,:) =  [ bottoms(5)    0.76+r    widths(4)        heights(1) ]; % >>  
  posbut(47,:) = [ bottoms(6)    0.76+r    widths(3)        heights(1) ]; % >>|  % NEW UGO

  posbut(23,:) = [ bottoms(1)    0.735+r   widths(1)    heights(1) ]; % Espacing/scale tag
  posbut(6,:) =  [ bottoms(1)    0.72+r    widths(1)    heights(1) ]; % Espacing/scale  

   posbut(48,:) = [ bottoms(2)   0.735+r   widths(1)    heights(1) ]; % NumChan tag % NEW UGO
   posbut(49,:) = [ bottoms(2)   0.72+r    widths(1)    heights(1) ]; % NumChan % NEW UGO

  posbut(52,:) = [ bottoms(2)    0.70+r    widths(1)    heights(1) ]; % Reset chan numbers to max auto % NEW UGO

  posbut(10,:) = [ bottoms(7)    0.70+r    widths(5)    heights(1) ]; % +  
  posbut(11,:) = [ bottoms(1)    0.70+r    widths(5)    heights(1) ]; % -  
  
  posbut(20,:) = [ 0.004   0.02    0.008    0.96 ]; % slider  
  
  % new TBT options #Ugo
  posbut(25,:) = [ bottoms(1)    0.675+r    widths(2)    heights(1) ]; % Title tag
  posbut(31,:) = [ bottoms(3)    0.66+r    1.5*widths(1)    heights(1) ]; % List of methods to run in the data
  posbut(33,:) = [ bottoms(1)    0.63+r    widths(2)    heights(1) ]; % List of Channel/Epoch Methods, drop box, select from list
  posbut(34,:) = [ bottoms(1)    0.60+r    widths(2)    heights(1) ]; % TextBox with options
  posbut(35,:) = [ bottoms(1)    0.58+r    widths(2)    heights(2) ]; % TextBox with option hints!
  posbut(36,:) = [ bottoms(1)    0.545+r    widths(1)    heights(1) ]; % Percent of Trials Tag
  posbut(37,:) = [ bottoms(2)    0.545+r    widths(1)    heights(1) ]; % Number of Channels Tag
  posbut(38,:) = [ bottoms(1)    0.525+r    widths(1)    heights(1) ]; % Percent of Trials box
  posbut(39,:) = [ bottoms(2)    0.525+r    widths(1)    heights(1) ]; % Number of Channels Box
  
  posbut(40,:) = [ bottoms(1)    0.505+r    widths(1)    heights(1) ]; % Run button % run code from box 1 and 2, add data to winrej, redraw
  
  %posbut(32,:) = [ 0.96    0.51+r    widths(1)    defaultsizes(1) ]; % Apply Rejections;
  
  posbut(41,:) = [ bottoms(2)    0.505+r    widths(1)    heights(1) ]; % Clear marks button
  %posbut(50,:) = [ 0.96    0.49+r    0.020    defaultsizes(1) ]; % UNDO BUTTON
  %posbut(53,:) = [ 0.98    0.49+r    0.020    defaultsizes(1) ]; % REDO BUTTON
 
  posbut(24,:) = [ bottoms(1)    0.48+r    widths(2)    heights(1) ]; % Topoplot tag

  %this doesnt do anything, just a place so I can remember what the
  %positions are, if I change up top I'll have to change here.
  g.headpos =     [ bottoms(8)   0.35+r      0.075    0.13 ]; %position of topoplot
  g.matrixpos =   [ bottoms(1)    0.35+r      widths(2)    0.13 ];  %position of matrix
 
  posbut(30,:) = [ bottoms(1)    0.32+r    widths(2)    heights(1) ]; % Counting marks tag #Ugo
  posbut(29,:) = [ bottoms(1)    0.30+r    widths(2)    heights(1) ]; % Counting marks #Ugo

  posbut(32,:) = [ bottoms(1)    0.28+r    widths(2)    heights(1) ]; % Apply Rejections;
  % deprecated
  %posbut(26,:) = [ 0.93    0.25    widths(2)    defaultsizes(1) ]; % Plot data difference #Ugo
% original = works
  
  posbut(54,:) = [ bottoms(1)    0.255+r    widths(1)    heights(1) ]; % plot FFT
  posbut(55,:) = [ bottoms(2)    0.255+r    widths(1)    heights(1) ]; % plot ICA headmaps
  %posbut(56,:) = [ bottoms(1)    0.43    widths(1)    defaultsizes(1) ]; % plot AVG FFT

   posbut(51,:) = [ bottoms(1)    0.23+r    widths(2)    heights(1) ]; % Epoched/Continuous Mode
   posbut(28,:) = [ bottoms(1)    0.21+r    widths(2)    heights(1) ]; % Rejecting/Interpolating Mode  
   posbut(27,:) = [ bottoms(1)    0.19+r    widths(2)    heights(1) ]; % Components/EEG SWITCH FUNCTION

% rotated  new vertical buttons
%   posbut(51,:) = [ 0.01    0.80    0.015    0.15 ]; % Components/EEG SWITCH FUNCTION  
%   posbut(28,:) = [ 0.01    0.625    0.015    0.17 ]; % Epoched/Continuous Mode
%   posbut(27,:) = [ 0.01    0.45    0.015    0.17 ]; % Rejecting/Interpolating Mode 
   
  posbut(57,:) = [ bottoms(1)    0.14+r    widths(2)    heights(1) ]; % Folder dropmenu
  posbut(58,:) = [ bottoms(1)    0.16+r    widths(2)    heights(1) ]; % Folder tag

   %posbut(59,:) = [ bottoms(1)    0.15    widths(2)    defaultsizes(2) ]; % Components/EEG SWITCH FUNCTION
  
  %posbut(43,:) = [ bottoms(1)    0.15    widths(2)    defaultsizes(2) ]; % RUN, TAG AND SAVE
  posbut(59,:) = [ bottoms(1)    0.11+r    widths(2)    heights(1) ]; % Save text tag
  posbut(44,:) = [ bottoms(1)    0.09+r    widths(2)    heights(1) ]; % SAVE TEXT EDIT

  posbut(45,:) = [ bottoms(1)    0.06+r    widths(2)    heights(1) ]; % SAVE FILE BUTTON
  posbut(42,:) = [ bottoms(1)    0.04+r    widths(2)    heights(1) ]; % store marks, transfer to eeglab #Ugo
  posbut(13,:) = [ bottoms(2)    0.02+r    widths(1)    heights(1) ]; % cancel/close

  %posbut(12,:) = [ bottoms(1)    0.02    widths(2)    defaultsizes(2) ]; % accept/close
  
%% NEW TEXT FOR THE CURRENT EEGLAB FILE
        
u(60) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(60,:),'Style','text','FontSize',8,...
	'Tag','Number of Channels tag','BackgroundColor',DEFAULT_FIG_COLOR,'string','Chans - Ref');

u(61) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(61,:),'Style','text','FontSize',10,...
	'Tag','Number of Channels','BackgroundColor',DEFAULT_FIG_COLOR,'string',[num2str(EEG.nbchan),' - ',EEG.ref]);

u(62) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(62,:),'Style','text','FontSize',8,...
	'Tag','Frames tag','BackgroundColor',DEFAULT_FIG_COLOR,'string','Frames - Rate');

u(63) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(63,:),'Style','text','FontSize',10,...
	'Tag','Frames','BackgroundColor',DEFAULT_FIG_COLOR,'string',[num2str(EEG.pnts),' - ',num2str(EEG.srate)]);

u(64) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(64,:),'Style','text','FontSize',8,...
	'Tag','Epochs tag','BackgroundColor',DEFAULT_FIG_COLOR,'string','Epochs-Events');

u(65) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(65,:),'Style','text','FontSize',10,...
	'Tag','Epochs','BackgroundColor',DEFAULT_FIG_COLOR,'string',[num2str(EEG.trials),' - ',num2str(size(EEG.event,2))]);

u(66) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(66,:),'Style','text','FontSize',8,...
	'Tag','Epochs time tag','BackgroundColor',DEFAULT_FIG_COLOR,'string','[Start End]');

u(67) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(67,:),'Style','text','FontSize',10,...
	'Tag','Epochs time','BackgroundColor',DEFAULT_FIG_COLOR,'string',['[',num2str(EEG.xmin),' ', num2str(EEG.xmax),']']);

u(68) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(68,:),'Style','text','FontSize',8,...
	'Tag','ICA weights tag','BackgroundColor',DEFAULT_FIG_COLOR,'string','ICA - Rank');

if ~isempty(EEG.icaact)
    tmpdata = reshape( EEG.data(1:EEG.nbchan,:,:), EEG.nbchan, EEG.pnts*EEG.trials);
    tmpdata = tmpdata - repmat(mean(tmpdata,2), [1 size(tmpdata,2)]); % zero mean
    tmprank = getrank(tmpdata(:,1:min(3000, size(tmpdata,2))));

    icatext = [num2str(size(EEG.icaact,1)),' - ', num2str(tmprank)];
else
    icatext = 'no';
end

u(69) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(69,:),'Style','text','FontSize',10,...
	'Tag','ICA weights','BackgroundColor',DEFAULT_FIG_COLOR,'string',icatext);

%% NEW BUTTONS SAVE AND LOAD
% load directory
%loaddircommand = ['findex = [1];try cd(EEG.filepath); catch, end; filecount = [1];files = dir(''*.set'');findex = find(strcmp({files.name}, EEG.filename));files = dir(''*.set'');set(findobj(''tag'',''FolderList''),''string'',{files(1:end).name},''value'',find(strcmp({files.name}, EEG.filename)));'];
% filelist
loadfilecommand = ['try cd(EEG.filepath); catch, end;files = dir(''*.set''); newEEG = pop_loadset(files(get(findobj(''tag'',''FolderList''),''value'')).name, pwd);[EEG,com] = pop_eegplot_adv(newEEG, 1, 2, 1, 1);[ALLEEG newEEG CURRENTSET] = eeg_store(ALLEEG, newEEG, CURRENTSET);'];

u(59) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(59,:),'Style','text','FontSize',8,...
	'Tag','save_file_title','BackgroundColor',DEFAULT_FIG_COLOR,'string','Enter Text to Add to Filename');

u(58) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(58,:),'Style','text','FontSize',8,...
	'Tag','load_dir_title','BackgroundColor',DEFAULT_FIG_COLOR,'string','Load File From This Folder');

u(57) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(57,:),'Style','popupmenu',...
    'Tag','FolderList','string','',    'callback',loadfilecommand);
load_directory(EEG,figh)
%eval(loaddircommand); % loads the folder of the file

%% Channel rejection callbacks
% get channels for partial interpolation
chaninterp = ['EEG.myVariables{1} = get(findobj(gcf, ''Tag'', ''Channel''),''string'');']; 
% select plot difference
plotdiffcom = ['EEG.myVariables{2} = get(findobj(gcf, ''Tag'', ''datadiff''),''Value'');'];
% get channels for complete interpolation
chaninterp2 = ['EEG.myVariables{3} = get(findobj(gcf, ''Tag'', ''Removal''),''string'');'];

displayep = ['eegplot_adv(''redraw'');'];
togglerej = ['eegplot_adv(''rejection'');'];
displaycomp = ['EEG.plotEp = 1 - EEG.plotEp; eegplot_adv(EEG,varargin);'];

%% --- start trial by trial options
% 

u(54) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(54,:),'Style','pushbutton',...
	'Tag','plotFFT','string','FFT(avg)','callback',['g = get(gcf,''UserData''); quick_spectra(g.EEG,40,2,''AVG'');']);

ICLcommand = ['g = get(gcf,''UserData''); [EEG,com] = quick_IClabel(g.EEG,[],[],[],[],[''eegplot_adv(''''MERGE_REJECTION'''');'']);'];

u(55) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(55,:),'Style','pushbutton',...
	'Tag','plotICLABEL','string','IClabel','callback',ICLcommand);

u(50) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(44,:),	'Style','edit', ...
	'Tag','SaveNowText','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string','');

    u(58) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(45,:),'Style','pushbutton',...
	'Tag','SaveNowButton','string','Save File with Text','callback',['eegplot_adv(''SAVE'');']);

%% heatmap title
  u(24) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(24,:),'Style','text','FontSize',8, ...
	'Tag','headmap','BackgroundColor',DEFAULT_FIG_COLOR,'string','Current Data Marks','TooltipString', ...
    ['Red lines: Rejected epochs',newline,...
    'Green lines: Epochs selected for partial interpolation',newline,...
    'Yellow lines: Channels/Components selected for interpolation/rejection',newline,...
    'Black dots: Parts of channels selected for interpolation or highlighted during rejection']);

%% TBT part modified from pop_TBT() scripts
if isstruct(EEG)
QuickLabDefs;

    g.eegmethods = ['ICA|',...
        'BSS EMG (AAR)|',...
        'Re-reference|'...
        'Re-epoch|'...
        'DipFit (par)|' ...
        'Any Script'];

    g.eegoptions = {...
        ['[], ''' ICATYPE ''' , 0'],...
        ['components, icatype, display'],...
        'quick_pca';...
        ...
        [''],...
        'window, windowshift',...
        'quick_bss2';...
        ...
        [' "AVG" '],...
        'choose reference(s)',...
        'quick_reref';...
        ...
        '0.600,2.648',...
        'time 1, time 2',...
        'quick_epoch';...
        ...
        ['[],1'],...
        '[components], dipoles',...
        'quick_dipfit';...
        ...
         [''],...
        'run any script',...
        '';...
        ...
        };

% g.eegoptions = {...
%         ['[], ''' ICATYPE ''' , 0'],...
%         ['components, icatype, display'],...
%         'quick_pca';...
%         ...
%         [''],...
%         'window, windowshift',...
%         'quick_bss2';...
%         ...
%         [' "AVG" '],...
%         'choose reference(s)',...
%         'quick_reref';...
%         ...
%         '',...
%         'remove surrounding channels',...
%         'quick_HM94';...
%         ...
%         '0.600,2.648',...
%         'time 1, time 2',...
%         'quick_epoch';...
%         ...
%         [''],...
%         'HM92, epoch [.6 2.658], ICA',...
%         '';...
%         ...
%         [''],...
%         'BSS + ICA',...
%         '';...
%         ...
%         ['[],1'],...
%         '[components], dipoles',...
%         'quick_dipfit';...
%         ...
%         [''],...
%         'ICA + ICL.8 + BSS + ICA',...
%         '';...
%         ...
%         };

    g.iclmethods = ['All but Brain and Other|' ...
        'Brain|'...
        'Muscle|'...
        'Eye|'...
        'Heart|'...
        'Line noise|'...
        'Channel noise|'...
        'Other'];

    g.icloptions = {...
        [' .8 1 '],...
        ['min max'],...
        '';...
        ...
        [' .3 0 '],...
        ['min max'],...
        '';...
        ...
        [' .8 1 '],...
        ['min max'],...
        '';...
        ...
        [' .8 1 '],...
        ['min max'],...
        '';...
        ...
        [' .8 1 '],...
        ['min max'],...
        '';...
        ...
        [' .8 1 '],...
        ['min max'],...
        '';...
        ...
        [' .8 1 '],...
        ['min max'],...
        '';...
        ...
        [' .8 1 '],...
        ['min max'],...
        '';...
        ...
        };

    g.tbtmethods = ['Abnormal values|'...
        'Abnormal trends|'...
        'Improbable data|'...
        'Abnormal distributions|'...
        'Abnormal spectra|'...
        'Max-Min Threshold|'...
        'Detect Flatline (cleanline)|' ...
        'Detect Channel Pops (by Ugo)'];
    
    g.tbtoptions = {...
        ['[1:57,59,60],-150 , 150 ,' num2str(EEG.xmin) ' , ' num2str(EEG.xmax)],...
        'chans,low/up thresh, starttime, endtime',...
        'pop_eegthresh';...
        ...
        ['[1:57,59,60],',num2str(EEG.pnts) ' , 0.5 , 0.3'],...
        'chans,winsize, maxslope, minR',...
        'pop_rejtrend';...
        ...
        '[1:57,59,60],3 , 3',...
        'chans,locthresh, globthresh',...
        'pop_jointprob';...
        ...
        '[1:57,59,60],3 , 3',...
        'chans,locthresh, globthresh',...
        'pop_rejkurt';...
        ...
        ['[1:57,59,60],''method'' , ''FFT'' , ''threshold'' , [-70 , 15] ,''freqlimits'' , [20 , 55]'],...
        'chans,th in Db, limits in Hz >34',...
        'pop_rejspec';...
        ...
        ['[1:57,59,60],[1:' num2str(EEG.nbchan) '],[' num2str([EEG.xmin EEG.xmax]*1000) '],100,' num2str([EEG.xmax - EEG.xmin]*1000) ',1,0'],...
        'chans,chRange,timeRange,minmaxThresh,winSize,stepSize,maW',...
        'pop_eegmaxmin';...
        ...
        ['[1:57,59,60],5, 20'],...
        ['chans,fl duration, max jitter'],...
        '';...
        ...
        ['[1:57,59,60],{5, 8, 100, 2, [],''mean''}'],...
        ['chans,SumWindow, StdRej, max rej win, Chancomps, type'],...
        '';...
        };
else
    g.tbtmethods = {'0','0'};
    g.tbtoptions = {'0','0'};
end

    g.plotmethods = ['Plot Spectra|' ...
        'Plot IClabel|'...
        'Plot Component ERPs'];
    
    g.plotoptions = {...
        ['40, 2, []'],...
        ['lowpass, highpass, reference'],...
        '';...
        ...
        ['[]'],...
        'components, lowpass, highpass',...
        '';...
        ...
        ['{2,[],[]}'],...
        'type, reference, project to channel',...
        '';...
        };

g.allmethods = ['TBT|' ...
        'QUICKLAB|'...
        'ICLABEL|' ...
        'QUICKLAB PLOTS'];

g.currentoptions = g.tbtoptions;

% Choose Methods tag
  u(25) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(25,:),'Style','text','FontSize',8, ...
	'Tag','ListTag','BackgroundColor',DEFAULT_FIG_COLOR,'string','Select Library of Functions');

% Functions Library
  u(32) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(31,:),'Style','popupmenu','HorizontalAlignment', 'center','FontSize',10,...
    'Tag','ListPopup','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string',g.allmethods,'callback',@change_list,'TooltipString','Select a library of functions');

% methods
  u(33) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(33,:),'Style','popupmenu',...
	'Tag','ALLmethods','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string',g.tbtmethods,'callback',@change_options,'TooltipString','Select a function of the chosen library');

% options
  u(34) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(34,:),'Style','edit',...
	'Tag','ALLoptions','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string',g.tbtoptions{1},'TooltipString','Options for the selected function');

% options hints
  u(35) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(35,:),'Style','text','FontSize',8,...
    'Tag','ALLhints','BackgroundColor',DEFAULT_FIG_COLOR,'string',g.tbtoptions{1,2},'TooltipString',['Hints for the function options,',newline,g.tbtoptions{1,2}]);
% hint

% tag
  u(36) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(36,:),'Style','text','FontSize',8,...
	'Tag','TBT%tag','BackgroundColor',DEFAULT_FIG_COLOR,'string','% Trials 4 rej.','TooltipString','Minimal percentage of trials necessary for a channel to be selected for rejection');

  u(37) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(37,:),'Style','text','FontSize',8,...
	'Tag','TBTnchanstag','BackgroundColor',DEFAULT_FIG_COLOR,	'string','# Chans 4 rej.','TooltipString','Minimal number of channels necessary for a trial to be selected for rejection');

  u(38) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(38,:),'Style','edit',...
	'Tag','TBT%','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string','60');

  u(39) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(39,:), 'Style','edit',...
	'Tag','TBTnchans','BackgroundColor',DEFAULT_PLOT_BACKGROUND, 'string','1');	

  u(40) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(40,:), ...
    'Tag','TBT','BackgroundColor',DEFAULT_OFF_COLOR,'string','Run','Callback', 'eegplot_adv(''METHODS'');' );

  u(60) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(32,:), ...
	'Tag','APPLY','BackgroundColor',DEFAULT_OFF_COLOR,'string','Apply Changes',	'Callback', ['eegplot_adv(''APPLY'');'] );

  %posbut(32
  u(41) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(41,:),...
	'Tag','ClearMarks','BackgroundColor',DEFAULT_OFF_COLOR,'string','Clear Marks','Callback', ['eegplot_adv(''ClearMarks'');']);

%% Save, Tag and ICA attempts #Ugo 5/27/2022
% u(43) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(43,:),
% 	'Tag','SaveTagICA', 'BackgroundColor',[.5 1 0.5],'string','Tag, Save & ICA','Callback', ['eegplot_adv(''saveandtag'')'] );

g.scripts = ['BSS|' ...
        'ICA|'...
        'Reference|'...
        'Epoch|'...
        'Channel Reduction'];

if g.EEG.plotchannels == 1
    cmodecolor = DEFAULT_ON_COLOR;
    cmode = 'Show ICA'; 
else
    cmodecolor = DEFAULT_OFF_COLOR;
    cmode = 'Show EEG'; 
end

u(45) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(51,:),...
	'Tag','SWITCH','BackgroundColor',cmodecolor,'string',cmode,'Callback', ['eegplot_adv(''SWITCH'');']);

% u(46) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(50,:), ...
% 	'Tag','UNDO', 'BackgroundColor',[.7 .7 1],'string','Undo','Callback', ['eegplot_adv(''UNDO'')']);
% 
% u(47) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(53,:),'Tag','REDO','BackgroundColor',[.7 .7 1],'string','Redo','Callback', ['eegplot_adv(''REDO'')']);

%% channel or epoch, rejection or interpolation buttons #Ugo

 u(27) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(27,:),...
	'Tag','Rejection','BackgroundColor',DEFAULT_ON_COLOR,'string','Interpolation Mode','Callback', togglerej);

if g.trialstag == -1
    modecolor = DEFAULT_OFF_COLOR;
    mode = 'Show Epoch';
else
    modecolor = DEFAULT_ON_COLOR;
    mode = 'Hide Epoch';
end

 u(28) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(28,:),...
	'Tag','Display', 'BackgroundColor',modecolor,'string',mode,'Callback', displayep );

%% number of marked areas for control #Ugo

  u(29) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(29,:),'Style','text','FontSize',8,...
	'Tag','Count_Trials','BackgroundColor',DEFAULT_FIG_COLOR,'string','');

  u(30) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(30,:),'Style','text','FontSize',8,...
	'Tag','Count_Channels','BackgroundColor',DEFAULT_FIG_COLOR,'string','');

%% arrows to move between marked winrej

  u(70) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(70,:),'Style','pushbutton','FontSize',8,...
	'Tag','GoBackWinrej','BackgroundColor',DEFAULT_FIG_COLOR,'string','<','Callback',{@draw_data,figh,11,[],[],ax1});

  u(71) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(71,:),'Style','pushbutton','FontSize',8,...
	'Tag','GoForwardWinrej','BackgroundColor',DEFAULT_FIG_COLOR,'string','>','Callback',{@draw_data,figh,12,[],[],ax1});

%% plot data difference checkbox

% u(26)= uicontrol('Parent',figh, ...
% 	'Units', 'normalized', ...
% 	'BackgroundColor',DEFAULT_PLOT_BACKGROUND, ...
% 	'Position', posbut(26,:), ...
% 	'Style','checkbox', ...
% 	'FontSize',8,...
% 	'Tag','datadiff',...
% 	'string','plot Data Difference',...
%     'Callback', plotdiffcom );

%% Five move buttons: |< << < text > >> >|
% NEW: GOES TO THE BEGGINING % UGO
  u(46) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(46,:),'FontSize',8,...
	'Tag','Pushbutton0','string','|<','Callback',{@draw_data,figh,8,[],[],ax1});

  u(1) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(1,:),'FontSize',8,...
	'Tag','Pushbutton1','string','<<','Callback',{@draw_data,figh,1,[],[],ax1});

  u(2) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(2,:), ...
	'Tag','Pushbutton2','string','<','Callback',{@draw_data,figh,2,[],[],ax1});

  u(5) = uicontrol('Parent',figh,'Units', 'normalized',	'Position', posbut(5,:),'Style','edit',...
	'Tag','EPosition','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string', fastif(g.trialstag(1) == -1, '0', '1'),'Callback', {@draw_data,figh,0,[],[],ax1});

  u(3) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(3,:), ...
	'Tag','Pushbutton3','string','>','Callback',{@draw_data,figh,3,[],[],ax1});

  u(4) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(4,:),'FontSize',8, ...
	'Tag','Pushbutton4','string','>>','Callback',{@draw_data,figh,4,[],[],ax1});

  % NEW GO TO THE END #UGO
  u(47) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(47,:), 'FontSize',8,...
	'Tag','Pushbutton5','string','>|','Callback',{@draw_data,figh,7,[],[],ax1});

%% Channels, position, value and tag
% Values of time/value and freq/power in GUI
  if g.isfreq
      u15_string =  'Freq';
      u16_string  = 'Power';
  else
      u15_string =  'Time';
      u16_string  = 'Value';
  end
      
  u(48)= uicontrol('Parent',figh,'Units','normalized','Position', posbut(48,:),'Style','text','FontSize',8,...
	'Tag','NumChansTag','BackgroundColor',DEFAULT_FIG_COLOR,'string','Chan Display');

  u(23)= uicontrol('Parent',figh,'Units','normalized','Position', posbut(23,:),'Style','text','FontSize',8,...
	'Tag','thescale','BackgroundColor',DEFAULT_FIG_COLOR,'string','Scale');

  u(15) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(15,:),'Style','text','FontSize',8,...
	'Tag','Etimename','BackgroundColor',DEFAULT_FIG_COLOR,'string',u15_string);

  u(16) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(16,:),'Style','text','FontSize',8,...
	'Tag','Evaluename','BackgroundColor',DEFAULT_FIG_COLOR,'string',u16_string);

  u(14) = uicontrol('Parent',figh,'Units','normalized','Position', posbut(14,:),'Style','text','FontSize',8,...
	'Tag','Eelecname','BackgroundColor',DEFAULT_FIG_COLOR,'string','Chan/Comp');

  u(09) = uicontrol('Parent',figh,'Units','normalized','Position', posbut(7,:),'Style','text','FontSize',10, ...
	'Tag','Eelec','string',' ','BackgroundColor',DEFAULT_FIG_COLOR);

  u(10) = uicontrol('Parent',figh,'Units','normalized','Position', posbut(8,:),'Style','text','FontSize',10,...
	'Tag','Etime','BackgroundColor',DEFAULT_FIG_COLOR,'string','0.00');

  u(11) = uicontrol('Parent',figh,'Units','normalized','Position', posbut(9,:),'Style','text','FontSize',10, ...
	'Tag','Evalue','BackgroundColor',DEFAULT_FIG_COLOR,'string','0.00');

%% Text edit fields: NumChans

  u(49) = uicontrol('Parent',figh, ...
	'Units', 'normalized','Position', posbut(49,:),'Style','edit', ...
	'Tag','NumChan','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string',num2str(g.chans),'Callback', 'eegplot_adv(''winelec_text'')' );

  %% Text edit fields: ESpacing
    u(6) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(6,:),'Style','edit', ...
    'Tag','ESpacing','BackgroundColor',DEFAULT_PLOT_BACKGROUND,'string',num2str(g.spacing),'Callback', {@change_scale,figh,0,ax1} );

%% Slider for vertical motion
  u(20) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(20,:),'Style','slider', ...
   'visible', 'off','sliderstep', [0.9 1],'Tag','eegslider',...
   'callback',{@draw_data,figh,0,[],[],ax1,'g.elecoffset = get(gcbo, ''value'')*(g.chans-g.dispchans);'}, ...
   'value', 0);


%% ESpacing buttons: + -
  u(7) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(10,:), ...
	'Tag','Pushbutton5','string','+','FontSize',10,'Callback',{@change_scale,figh,1,ax1});

  u(8) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(11,:), ...
	'Tag','Pushbutton6','string','-','FontSize',10,'Callback',{@change_scale,figh,2,ax1});
  
  u(61) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(52,:), ...
	'Tag','Pushbutton6','string','Show All','FontSize',10,'Callback',['eegplot_adv(''winelec_auto'')']);

%% Button for Normalizing data
u(21) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(21,:), ...
    'Tag','Norm','string','Norm', 'callback', {@normalize_chan,figh});

cb_envelope = ['g = get(gcbf,''userdata'');'...
    'hmenu = findobj(gcf, ''Tag'', ''Envelope_menu'');' ...
    'g.envelope = ~g.envelope;' ...
    'set(gcbf,''userdata'',g);'...
    'set(gcbo,''string'',fastif(g.envelope,''Spread'',''Stack''));' ...
    'set(hmenu, ''Label'', fastif(g.envelope,''Spread channels'',''Stack channels''));' ...
    'eegplot_adv(''drawp'',0);clear g;'];

%% Button to plot envelope of data
u(22) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(22,:), ...
    'Tag','Envelope','string','Stack', 'callback', cb_envelope);

  if isempty(g.command) tmpcom = 'fprintf(''Rejections saved in variable TMPREJ\n'');';   
  else tmpcom = g.command;
  end
  closecommand = ['g = get(gcbf,''userdata''); EEG = g.EEG; if g.children, delete(g.children); end'...
                 'delete(gcbf);' ...
                 'eval(get(findobj(''tag'',''LoadDir''),''Callback''));' ...
                 'eval(get(findobj(''tag'',''LoadFileList''),''Callback''));'];

  acceptcommand = [ 'g = get(gcbf, ''userdata'');' ... 
                    'TMPREJ = g.winrej;' ...
                    'if isfield(g, ''eloc_file'') && isfield(g.eloc_file, ''badchan''); '...
                         'TMPREJCHN = find([g.eloc_file.badchan]); '...
                    'else TMPREJCHN = [];'...
                    'end ' ...
                          closecommand ...
		  				  tmpcom ...
                    '; clear g;']; % quitting expression
  if ~isempty(g.command)
% 	  u(12) = uicontrol('Parent',figh, ...
% 						'Units', 'normalized', ...
% 						'Position',posbut(12,:), ...
% 						'Tag','Accept',...
% 						'string',g.butlabel, 'callback', acceptcommand);
  end

%   Commented/deprecated the close button for UX purposes
%   u(13) = uicontrol('Parent',figh, ...
% 	'Units', 'normalized', ...
% 	'Position',posbut(13,:), ...
% 	'string',fastif(isempty(g.command),'CLOSE', 'CLOSE'), 'callback', ...
% 		[	'g = get(gcbf, ''userdata'');' ...
%             'if g.children, delete(g.children); end;' ...
% 			'close(gcbf);'] );

% save button #Ugo
if isempty(g.command) 
    tmpsavecom = 'fprintf(''Rejections saved in variable TMPREJ\n'');';   
else 
    if g.EEG.plotchannels == 1
        tmpsavecom = g.savecommand;
    else
        tmpsavecom = g.savecommand2;
    end
end
  savecommand = [ 'g = get(gcbf, ''userdata'');' ...  
                'TMPEEG = g.EEG;' ...
                    'TMPREJ = g.winrej;' ...
                    'if isfield(g, ''eloc_file'') && isfield(g.eloc_file, ''badchan''); '...
                         'TMPREJCHN = find([g.eloc_file.badchan]); '...
                    'else TMPREJCHN = [];'...
                    'end; ' ...
		  				  tmpsavecom]; % quitting expression
                      
  if ~isempty(g.savecommand)
    
      u(42) = uicontrol('Parent',figh,'Units', 'normalized','Position', posbut(42,:), ...
	   'Tag','SaveButton', 'BackgroundColor',[.5 1 0.5],'string','Transfer to EEGLAB','Callback', savecommand );

  end

 acceptandsavecommand = [savecommand acceptcommand];

  if ~isempty(g.events)
      u(17) = uicontrol('Parent',figh,'Units', 'normalized','Position',posbut(17,:), ...
                        'string', 'Events', 'callback', 'eegplot_adv(''drawlegend'', gcbf);');
  end

  for i = 1: length(u) % Matlab 2014b compatibility
      if isprop(eval(['u(' num2str(i) ')']),'Style')
          set(u(i),'Units','Normalized');
      end
  end
  
  % %%%%%%%%%%%%%%%%%%%%%%%%%%%
  % Set up uimenus
  % %%%%%%%%%%%%%%%%%%%%%%%%%%%
  
  % Figure Menu %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  m(7) = uimenu('Parent',figh,'Label','Figure');
  m(8) = uimenu('Parent',m(7),'Label','Print');
  uimenu('Parent',m(7),'Label','Edit figure', 'Callback', 'eegplot_adv(''noui'');');
  uimenu('Parent',m(7),'Label','Accept and close','Tag','AcceptAndSave', 'Callback', acceptandsavecommand );
  uimenu('Parent',m(7),'Label','Cancel and close', 'Callback','delete(gcbf)')
  
  % Portrait %%%%%%%%

  timestring = ['[OBJ1,FIG1] = gcbo;',...
	        'PANT1 = get(OBJ1,''parent'');',...
	        'OBJ2 = findobj(''tag'',''orient'',''parent'',PANT1);',...
		'set(OBJ2,''checked'',''off'');',...
		'set(OBJ1,''checked'',''on'');',...
		'set(FIG1,''PaperOrientation'',''portrait'');',...
		'clear OBJ1 FIG1 OBJ2 PANT1;'];
		
  uimenu('Parent',m(8),'Label','Portrait','checked',...
      'on','tag','orient','callback',timestring)
  
  % Landscape %%%%%%%
  timestring = ['[OBJ1,FIG1] = gcbo;',...
	        'PANT1 = get(OBJ1,''parent'');',...
	        'OBJ2 = findobj(''tag'',''orient'',''parent'',PANT1);',...
		'set(OBJ2,''checked'',''off'');',...
		'set(OBJ1,''checked'',''on'');',...
		'set(FIG1,''PaperOrientation'',''landscape'');',...
		'clear OBJ1 FIG1 OBJ2 PANT1;'];
  
  uimenu('Parent',m(8),'Label','Landscape','checked',...
      'off','tag','orient','callback',timestring)

  % Print command %%%%%%%
  uimenu('Parent',m(8),'Label','Print','tag','printcommand','callback',...
  		['RESULT = inputdlg2( { ''Command:'' }, ''Print'', 1,  { ''print -r72'' });' ...
		 'if size( RESULT,1 ) ~= 0' ... 
		 '  eval ( RESULT{1} );' ...
		 'end;' ...
		 'clear RESULT;' ]);
  
  % Display Menu %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  m(1) = uimenu('Parent',figh,...
      'Label','Display', 'tag', 'displaymenu');
  
  % window grid %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  % userdata = 4 cells : display yes/no, color, electrode yes/no, 
  %                      trial boundary adapt yes/no (1/0)  
  m(11) = uimenu('Parent',m(1),'Label','Data select/mark', 'tag', 'displaywin', ...
            'userdata', { 1, [0.8 1 0.8], 0, fastif( g.trialstag(1) == -1, 0, 1)});

          uimenu('Parent',m(11),'Label','Hide marks','Callback', ...
  	        ['g = get(gcbf, ''userdata'');' ...
            'if ~g.winstatus' ... 
            '  set(gcbo, ''label'', ''Hide marks'');' ...
            'else' ...
            '  set(gcbo, ''label'', ''Show marks'');' ...
            'end;' ...
            'g.winstatus = ~g.winstatus;' ...
            'set(gcbf, ''userdata'', g);' ...
            'eegplot_adv(''drawb''); clear g;'] )

	% color %%%%%%%%%%%%%%%%%%%%%%%%%%
    if isunix % for some reasons, does not work under Windows
        uimenu('Parent',m(11),'Label','Choose color', 'Callback', ...
               [ 'g = get(gcbf, ''userdata'');' ...
                 'g.wincolor = uisetcolor(g.wincolor);' ...
                 'set(gcbf, ''userdata'', g ); ' ...
                 'clear g;'] )
    end

  % plot durations
  % --------------
  if g.ploteventdur && isfield(g.events, 'duration')
      disp(['Use menu "Display > Hide event duration" to hide colored regions ' ...
           'representing event duration']);
  end
  if isfield(g.events, 'duration')
      uimenu('Parent',m(1),'Label',fastif(g.ploteventdur, 'Hide event duration', 'Plot event duration'),'Callback', ...
             ['g = get(gcbf, ''userdata'');' ...
              'if ~g.ploteventdur' ... 
              '  set(gcbo, ''label'', ''Hide event duration'');' ...
              'else' ...
              '  set(gcbo, ''label'', ''Show event duration'');' ...
              'end;' ...
              'g.ploteventdur = ~g.ploteventdur;' ...
              'set(gcbf, ''userdata'', g);' ...
              'eegplot_adv(''drawb''); clear g;'] )
  end

  % X grid %%%%%%%%%%%%
  m(3) = uimenu('Parent',m(1),'Label','Grid');
  timestring = ['FIGH = gcbf;',...
	            'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
	            'if size(get(AXESH,''xgrid''),2) == 2' ... %on
		        '  set(AXESH,''xgrid'',''off'');',...
		        '  set(gcbo,''label'',''X grid on'');',...
		        'else' ...
		        '  set(AXESH,''xgrid'',''on'');',...
		        '  set(gcbo,''label'',''X grid off'');',...
		        'end;' ...
		        'clear FIGH AXESH;' ];
  uimenu('Parent',m(3),'Label',fastif(strcmp(g.xgrid, 'off'), ...
         'X grid on','X grid off'), 'Callback',timestring)
  
  % Y grid %%%%%%%%%%%%%
  timestring = ['FIGH = gcbf;',...
	            'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
	            'if size(get(AXESH,''ygrid''),2) == 2' ... %on
		        '  set(AXESH,''ygrid'',''off'');',...
		        '  set(gcbo,''label'',''Y grid on'');',...
		        'else' ...
		        '  set(AXESH,''ygrid'',''on'');',...
		        '  set(gcbo,''label'',''Y grid off'');',...
		        'end;' ...
		        'clear FIGH AXESH;' ];
  uimenu('Parent',m(3),'Label',fastif(strcmp(g.ygrid, 'off'), ...
         'Y grid on','Y grid off'), 'Callback',timestring)

  % Grid Style %%%%%%%%%
  m(5) = uimenu('Parent',m(3),'Label','Grid Style');
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'',''--'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','- -','Callback',timestring)
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'',''-.'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','_ .','Callback',timestring)
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'','':'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','. .','Callback',timestring)
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'',''-'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','__','Callback',timestring)
  
  % Submean menu %%%%%%%%%%%%%
  cb =       ['g = get(gcbf, ''userdata'');' ...
              'if strcmpi(g.submean, ''on''),' ... 
              '  set(gcbo, ''label'', ''Remove DC offset'');' ...
              '  g.submean =''off'';' ...
              'else' ...
              '  set(gcbo, ''label'', ''Do not remove DC offset'');' ...
              '  g.submean =''on'';' ...
              'end;' ...
              'set(gcbf, ''userdata'', g);' ...
              'eegplot_adv(''drawp'', 0); clear g;'];
  uimenu('Parent',m(1),'Label',fastif(strcmp(g.submean, 'on'), ...
         'Do not remove DC offset','Remove DC offset'), 'Callback',cb)

  % Scale Eye %%%%%%%%%
  timestring = ['[OBJ1,FIG1] = gcbo;',...
	        'eegplot_adv(''scaleeye'',OBJ1,FIG1);',...
		'clear OBJ1 FIG1;'];
  m(7) = uimenu('Parent',m(1),'Label','Show scale','Callback',timestring);
  
  % Title %%%%%%%%%%%%
  uimenu('Parent',m(1),'Label','Title','Callback','eegplot_adv(''title'')')
  
  % Stack/Spread %%%%%%%%%%%%%%%
  cb =       ['g = get(gcbf, ''userdata'');' ...
              'hbutton = findobj(gcf, ''Tag'', ''Envelope'');' ...  % find button
              'if g.envelope == 0,' ... 
              '  set(gcbo, ''label'', ''Spread channels'');' ...
              '  g.envelope = 1;' ...
              '  set(hbutton, ''String'', ''Spread'');' ...
              'else' ...
              '  set(gcbo, ''label'', ''Stack channels'');' ...
              '  g.envelope = 0;' ...
              '  set(hbutton, ''String'', ''Stack'');' ...
              'end;' ...
              'set(gcbf, ''userdata'', g);' ...
              'eegplot_adv(''drawp'', 0); clear g;'];
  uimenu('Parent',m(1),'Label',fastif(g.envelope == 0, ...
         'Stack channels','Spread channels'), 'Callback',cb, 'Tag', 'Envelope_menu')
     
  % Normalize/denormalize %%%%%%%%%%%%%%%
  uimenu('Parent',m(1),'Label',fastif(g.envelope == 0, ...
         'Normalize channels','Denormalize channels'), 'Callback', {@normalize_chan,figh}, 'Tag', 'Normalize_menu')

  
  % Settings Menu %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  m(2) = uimenu('Parent',figh,...
      'Label','Settings'); 
  
  % Window %%%%%%%%%%%%
  uimenu('Parent',m(2),'Label','Time range to display',...
      'Callback','eegplot_adv(''window'')')
  
  % Electrode window %%%%%%%%
  uimenu('Parent',m(2),'Label','Number of channels to display',...
      'Callback','eegplot_adv(''winelec'')')
  
  % Electrodes %%%%%%%%
  m(6) = uimenu('Parent',m(2),'Label','Channel labels');
  
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'YTICK = get(AXESH,''YTick'');',...
		'YTICK = length(YTICK);',...
		'set(AXESH,''YTickLabel'',flipud(char(num2str((1:YTICK-1)''),'' '')));',...
		'clear FIGH AXESH YTICK;'];
  uimenu('Parent',m(6),'Label','Show number','Callback',timestring)
  uimenu('Parent',m(6),'Label','Load .loc(s) file',...
      'Callback','eegplot_adv(''loadelect'');')
  
  % Zooms %%%%%%%%
 % if ismatlab && verLessThan('matlab','8.4.0')
 %     zm = uimenu('Parent',m(2),'Label','Zoom off/on');
 %     commandzoom = [ 'set(gcbf, ''WindowButtonDownFcn'', [ ''zoom(gcbf,''''down''''); eegplot_adv(''''zoom'''', gcbf, 1);'' ]);' ...
 %         'tmpg = get(gcbf, ''userdata'');' ...
 %         'clear tmpg tmpstr;'];
 %     uimenu('Parent',zm,'Label','Zoom on', 'callback', commandzoom);
 %     uimenu('Parent',zm,'Label','Zoom off', 'separator', 'on', 'callback', ...
 %         ['zoom(gcbf, ''off''); tmpg = get(gcbf, ''userdata'');' ...
 %         'set(gcbf, ''windowbuttondownfcn'', tmpg.commandselect{1});' ...
 %         'set(gcbf, ''windowbuttonupfcn'', tmpg.commandselect{3});' ...
 %         'clear tmpg;' ]);
 % else
 %      % This is failing for us http://undocumentedmatlab.com/blog/enabling-user-callbacks-during-zoom-pan
 %      uimenu('Parent',m(2),'Label','Zoom off/on', 'callback', 'warning(''FIXME: Zoom not work in MATLAB >= 8.4.0'')');
 % end
      
  uimenu('Parent',m(2),'Label', 'Help', 'callback', 'pophelp(''eegplot_adv'');'); %changed from figh to m(2) > settings

  % Events %%%%%%%%
  ev = uimenu('Parent',m(2),'Label','Events');
  comeventmaxstring   = [ 'tmpg = get(gcbf, ''userdata'');' ...
                'tmpg.plotevent = ''on'';' ...
                'set(gcbf, ''userdata'', tmpg); clear tmpg; eegplot_adv(''emaxstring'');']; % JavierLC      
  comeventleg  = [ 'eegplot_adv(''drawlegend'', gcbf);'];
    
  uimenu('Parent',ev,'Label','Events on'    , 'callback', {@draw_data,figh,0,[],[],ax1,'g.plotevent = ''on'';'},  'enable', fastif(isempty(g.events), 'off', 'on'));
  uimenu('Parent',ev,'Label','Events off'   , 'callback', {@draw_data,figh,0,[],[],ax1,'g.plotevent = ''off'';'}, 'enable', fastif(isempty(g.events), 'off', 'on'));
  uimenu('Parent',ev,'Label','Events'' string length'   , 'callback', comeventmaxstring, 'enable', fastif(isempty(g.events), 'off', 'on')); % JavierLC
  uimenu('Parent',ev,'Label','Events'' legend', 'callback', comeventleg , 'enable', fastif(isempty(g.allevents), 'off', 'on'));
  

  % %%%%%%%%%%%%%%%%%
  % Set up autoselect                                                        
  % NOTE: commandselect{2} option has been moved to a
  %       subfunction to improve speed
  %%%%%%%%%%%%%%%%%%%

   mouse_motion_com = {'@eegplot_adv,''mouse_motion'';'};


  if ~isempty(g.ctrlselectcommand{1}) || ~isempty(g.ctrlselectcommand{3}) || ...
         ~isempty(g.selectcommand{1}) || ~isempty(g.selectcommand{3})
      g.commandselect{1} = [ 'if strcmp(get(gcbf, ''SelectionType''),''alt''),' ...
           g.ctrlselectcommand{1} '; else ' g.selectcommand{1} '; end;' ];
      g.commandselect{3} = [ 'if strcmp(get(gcbf, ''SelectionType''),''alt''),' ...
           g.ctrlselectcommand{3} '; else ' g.selectcommand{3} '; end;' ];
      set(figh, 'WindowButtonDownFcn',   g.commandselect{1});
      set(figh, 'WindowButtonupFcn',     g.commandselect{3});
  else
      set(figh, 'WindowButtonDownFcn',   {@mouse_down,figh});
      set(figh, 'WindowButtonupFcn',     {@mouse_up,figh});
  end

  set(figh, 'WindowScrollWheelFcn',  {@mouse_scroll_wheel,figh,ax0,ax1,u(10),u(11),u(9)});
  set(figh, 'WindowButtonMotionFcn', {@mouse_motion,figh,ax0,ax1,u(10),u(11),u(9)});
  %set(figh, 'windowbuttonmotionfcn', EEG = eegplot_adv('mouse_motion'));
  set(figh, 'WindowKeyPressFcn',     {@eegplot_readkey,figh,ax0,ax1,u(10),u(11),u(9)});
  set(figh, 'interruptible', 'on');
%  set(figh, 'busyaction', 'cancel');
%  set(figh, 'windowbuttondownfcn', commandpush);
%  set(figh, 'windowbuttonmotionfcn', commandmove);
%  set(figh, 'windowbuttonupfcn', commandrelease);

end % end of eegplot_create_ui

%% Local subfunctions (copied from eegplot_adv.m to maintain accessibility)

function tmprank2 = getrank(tmpdata)

tmprank = rank(tmpdata);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Here: alternate computation of the rank by Sven Hoffman
%tmprank = rank(tmpdata(:,1:min(3000, size(tmpdata,2)))); old code
covarianceMatrix = cov(tmpdata', 1);
[~, D] = eig (covarianceMatrix);
rankTolerance = 1e-7;
tmprank2=sum (diag (D) > rankTolerance);
if tmprank ~= tmprank2
    %fprintf('Warning: fixing rank computation inconsistency (%d vs %d) most likely because running under Linux 64-bit Matlab\n', tmprank, tmprank2);
    tmprank2 = min(tmprank, tmprank2);
end

function load_directory(EEG,fig)

if isstruct(EEG)
    findex = [1];
    try cd(EEG.filepath);
    catch
    end
    files = dir('*.set');
    findex = find(strcmp({files.name}, EEG.filename));
    set(findobj(fig,'tag','FolderList'),'string',{files(1:end).name},'value',find(strcmp({files.name}, EEG.filename)));
end
