function [g, u, m, modecolor, cmodecolor] = eegplot_create_ui(figh, g, data, EEG, ax0, ax1, colors, panels)
% eegplot_create_ui() - Create all UI controls and menus for eegplot_adv
%
% Usage:
%   [g, u, m, modecolor, cmodecolor] = eegplot_create_ui(figh, g, data, EEG, ax0, ax1, colors, panels)
%
% Inputs:
%   figh   - figure handle
%   g      - eegplot_adv userdata struct
%   data   - EEG data matrix
%   EEG    - EEG struct
%   ax0    - background axes handle
%   ax1    - EEG data axes handle
%   colors - struct with color/style defaults:
%            DEFAULT_FIG_COLOR, DEFAULT_PLOT_BACKGROUND, DEFAULT_PLOT_INTERP,
%            DEFAULT_ON_COLOR, DEFAULT_OFF_COLOR, DEFAULT_SPECIAL_COLOR,
%            DEFAULT_SPECIAL_TEXT, DEFAULT_AXIS_COLOR, BUTTON_COLOR,
%            DEFAULT_AXES_POSITION, DEFAULT_GRID_STYLE
%   panels - struct with tabbed panel layout handles:
%            .main, .side, .nav, .viewTabs, .dataTab,
%            .sideTabs, .infoTab, .marksTab, .methodsTab, .actionsTab
%
% Outputs:
%   g          - updated userdata struct
%   u          - array of uicontrol handles
%   m          - array of uimenu handles
%   modecolor  - color for the Display mode button
%   cmodecolor - color for the SWITCH (ICA/EEG) button

% Unpack color variables from struct
DEFAULT_FIG_COLOR       = colors.DEFAULT_FIG_COLOR;
DEFAULT_PLOT_BACKGROUND = colors.DEFAULT_PLOT_BACKGROUND;
DEFAULT_PLOT_INTERP     = colors.DEFAULT_PLOT_INTERP;
DEFAULT_ON_COLOR        = colors.DEFAULT_ON_COLOR;
DEFAULT_OFF_COLOR       = colors.DEFAULT_OFF_COLOR;
DEFAULT_SPECIAL_COLOR   = colors.DEFAULT_SPECIAL_COLOR;
DEFAULT_SPECIAL_TEXT    = colors.DEFAULT_SPECIAL_TEXT;
DEFAULT_AXIS_COLOR      = colors.DEFAULT_AXIS_COLOR;
BUTTON_COLOR            = colors.BUTTON_COLOR;
DEFAULT_AXES_POSITION   = colors.DEFAULT_AXES_POSITION;
DEFAULT_GRID_STYLE      = colors.DEFAULT_GRID_STYLE;

  %% ========================================================================
  %  NAV PANEL - horizontal row of navigation controls
  %  ========================================================================
  bw  = 0.05;   % button width
  bwn = 0.04;   % narrow button width
  ew  = 0.12;   % edit width
  bh  = 0.8;    % button height (fraction of navPanel)
  by  = 0.1;    % button y offset
  gap = 0.005;  % gap between controls
  x   = 0.005;

  % |< button
  u(46) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by bwn bh], 'FontSize', 8, ...
    'Tag', 'Pushbutton0', 'string', '|<', 'Callback', {@draw_data,figh,8,[],[],ax1});
  x = x + bwn + gap;

  % << button
  u(1) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by bw bh], 'FontSize', 8, ...
    'Tag', 'Pushbutton1', 'string', '<<', 'Callback', {@draw_data,figh,1,[],[],ax1});
  x = x + bw + gap;

  % < button
  u(2) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by bwn bh], ...
    'Tag', 'Pushbutton2', 'string', '<', 'Callback', {@draw_data,figh,2,[],[],ax1});
  x = x + bwn + gap;

  % EPosition edit
  u(5) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by ew bh], 'Style', 'edit', ...
    'Tag', 'EPosition', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, ...
    'string', fastif(g.trialstag(1) == -1, '0', '1'), ...
    'Callback', {@draw_data,figh,0,[],[],ax1});
  x = x + ew + gap;

  % > button
  u(3) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by bwn bh], ...
    'Tag', 'Pushbutton3', 'string', '>', 'Callback', {@draw_data,figh,3,[],[],ax1});
  x = x + bwn + gap;

  % >> button
  u(4) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by bw bh], 'FontSize', 8, ...
    'Tag', 'Pushbutton4', 'string', '>>', 'Callback', {@draw_data,figh,4,[],[],ax1});
  x = x + bw + gap;

  % >| button
  u(47) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by bwn bh], 'FontSize', 8, ...
    'Tag', 'Pushbutton5', 'string', '>|', 'Callback', {@draw_data,figh,7,[],[],ax1});
  x = x + bwn + gap * 4;

  % Scale tag
  u(23) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by 0.04 bh], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'thescale', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Scale');
  x = x + 0.04 + gap;

  % ESpacing edit
  u(6) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by 0.07 bh], 'Style', 'edit', ...
    'Tag', 'ESpacing', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, ...
    'string', num2str(g.spacing), 'Callback', {@change_scale,figh,0,ax1});
  x = x + 0.07 + gap;

  % + button
  u(7) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by 0.03 bh], ...
    'Tag', 'Pushbutton5', 'string', '+', 'FontSize', 10, ...
    'Callback', {@change_scale,figh,1,ax1});
  x = x + 0.03 + gap;

  % - button
  u(8) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by 0.03 bh], ...
    'Tag', 'Pushbutton6', 'string', '-', 'FontSize', 10, ...
    'Callback', {@change_scale,figh,2,ax1});
  x = x + 0.03 + gap * 4;

  % NumChans tag
  u(48) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by 0.06 bh], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'NumChansTag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Chan Display');
  x = x + 0.06 + gap;

  % NumChan edit
  u(49) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by 0.05 bh], 'Style', 'edit', ...
    'Tag', 'NumChan', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, ...
    'string', num2str(g.chans), 'Callback', 'eegplot_adv(''winelec_text'')');
  x = x + 0.05 + gap;

  % Show All button
  u(61) = uicontrol('Parent', panels.nav, 'Units', 'normalized', ...
    'Position', [x by 0.06 bh], ...
    'Tag', 'Pushbutton6', 'string', 'Show All', 'FontSize', 10, ...
    'Callback', ['eegplot_adv(''winelec_auto'')']);

  %% ========================================================================
  %  SLIDER - stays on the figure
  %  ========================================================================
  u(20) = uicontrol('Parent', figh, 'Units', 'normalized', ...
    'Position', [0.004 0.02 0.008 0.96], 'Style', 'slider', ...
    'visible', 'off', 'sliderstep', [0.9 1], 'Tag', 'eegslider', ...
    'callback', {@draw_data,figh,0,[],[],ax1,'g.elecoffset = get(gcbo, ''value'')*(g.chans-g.dispchans);'}, ...
    'value', 0);

  %% ========================================================================
  %  INFO TAB - stacked vertically
  %  ========================================================================
  margin = 0.05;
  tw     = 1 - 2*margin;   % text width
  h      = 0.04;            % row height
  hval   = 0.05;            % value row height
  tgap   = 0.005;           % gap between rows
  y      = 0.94;            % start from top

  % --- Cursor info section ---
  u(14) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Eelecname', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Chan/Comp');
  y = y - hval - tgap;

  u(09) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'Eelec', 'string', ' ', 'BackgroundColor', DEFAULT_FIG_COLOR);
  y = y - h - tgap * 2;

  if g.isfreq
      u15_string = 'Freq';
      u16_string = 'Power';
  else
      u15_string = 'Time';
      u16_string = 'Value';
  end

  u(15) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Etimename', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', u15_string);
  y = y - hval - tgap;

  u(10) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'Etime', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '0.00');
  y = y - h - tgap * 2;

  u(16) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Evaluename', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', u16_string);
  y = y - hval - tgap;

  u(11) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'Evalue', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '0.00');
  y = y - h - tgap * 4;

  % --- File info section ---
  u(60) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Number of Channels tag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Chans - Ref');
  y = y - hval - tgap;

  u(61) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'Number of Channels', 'BackgroundColor', DEFAULT_FIG_COLOR, ...
    'string', [num2str(EEG.nbchan), ' - ', EEG.ref]);
  y = y - h - tgap * 2;

  u(62) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Frames tag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Frames - Rate');
  y = y - hval - tgap;

  u(63) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'Frames', 'BackgroundColor', DEFAULT_FIG_COLOR, ...
    'string', [num2str(EEG.pnts), ' - ', num2str(EEG.srate)]);
  y = y - h - tgap * 2;

  u(64) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Epochs tag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Epochs-Events');
  y = y - hval - tgap;

  u(65) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'Epochs', 'BackgroundColor', DEFAULT_FIG_COLOR, ...
    'string', [num2str(EEG.trials), ' - ', num2str(size(EEG.event,2))]);
  y = y - h - tgap * 2;

  u(66) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Epochs time tag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '[Start End]');
  y = y - hval - tgap;

  u(67) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'Epochs time', 'BackgroundColor', DEFAULT_FIG_COLOR, ...
    'string', ['[', num2str(EEG.xmin), ' ', num2str(EEG.xmax), ']']);
  y = y - h - tgap * 2;

  u(68) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'ICA weights tag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'ICA - Rank');
  y = y - hval - tgap;

  if ~isempty(EEG.icaact)
      tmpdata = reshape(EEG.data(1:EEG.nbchan,:,:), EEG.nbchan, EEG.pnts*EEG.trials);
      tmpdata = tmpdata - repmat(mean(tmpdata,2), [1 size(tmpdata,2)]);
      tmprank = getrank(tmpdata(:,1:min(3000, size(tmpdata,2))));
      icatext = [num2str(size(EEG.icaact,1)), ' - ', num2str(tmprank)];
  else
      icatext = 'no';
  end

  u(69) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'text', 'FontSize', 10, ...
    'Tag', 'ICA weights', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', icatext);
  y = y - h - tgap * 4;

  % --- Folder browser section ---
  u(58) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'load_dir_title', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Load File From This Folder');
  y = y - hval - tgap;

  loadfilecommand = ['try cd(EEG.filepath); catch, end;files = dir(''*.set''); newEEG = pop_loadset(files(get(findobj(''tag'',''FolderList''),''value'')).name, pwd);[EEG,com] = pop_eegplot_adv(newEEG, 1, 2, 1, 1);[ALLEEG newEEG CURRENTSET] = eeg_store(ALLEEG, newEEG, CURRENTSET);'];

  u(57) = uicontrol('Parent', panels.infoTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'popupmenu', ...
    'Tag', 'FolderList', 'string', '', 'callback', loadfilecommand);
  load_directory(EEG, figh)

  %% ========================================================================
  %  MARKS TAB - stacked vertically
  %  ========================================================================
  y = 0.94;

  % Heatmap/topoplot title
  u(24) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'headmap', 'BackgroundColor', DEFAULT_FIG_COLOR, ...
    'string', 'Current Data Marks', 'TooltipString', ...
    ['Red lines: Rejected epochs', newline, ...
     'Green lines: Epochs selected for partial interpolation', newline, ...
     'Yellow lines: Channels/Components selected for interpolation/rejection', newline, ...
     'Black dots: Parts of channels selected for interpolation or highlighted during rejection']);
  y = y - h - tgap * 2;

  % < prev mark  |  > next mark
  halfW = (tw - gap) / 2;
  u(70) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y halfW h], 'Style', 'pushbutton', 'FontSize', 8, ...
    'Tag', 'GoBackWinrej', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '<', ...
    'Callback', {@draw_data,figh,11,[],[],ax1});

  u(71) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin+halfW+gap y halfW h], 'Style', 'pushbutton', 'FontSize', 8, ...
    'Tag', 'GoForwardWinrej', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '>', ...
    'Callback', {@draw_data,figh,12,[],[],ax1});
  y = y - h - tgap * 2;

  % Count trials
  u(29) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Count_Trials', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '');
  y = y - h - tgap;

  % Count channels
  u(30) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'Count_Channels', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '');
  y = y - h - tgap * 2;

  % Rejection/Interpolation mode toggle
  displayep  = ['eegplot_adv(''redraw'');'];
  togglerej  = ['eegplot_adv(''rejection'');'];

  u(27) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], ...
    'Tag', 'Rejection', 'BackgroundColor', DEFAULT_ON_COLOR, ...
    'string', 'Interpolation Mode', 'Callback', togglerej);
  y = y - h - tgap * 2;

  % EEG/ICA switch
  if g.EEG.plotchannels == 1
      cmodecolor = DEFAULT_ON_COLOR;
      cmode = 'Show ICA';
  else
      cmodecolor = DEFAULT_OFF_COLOR;
      cmode = 'Show EEG';
  end

  u(45) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], ...
    'Tag', 'SWITCH', 'BackgroundColor', cmodecolor, ...
    'string', cmode, 'Callback', ['eegplot_adv(''SWITCH'');']);
  y = y - h - tgap * 2;

  % Epoch display toggle
  if g.trialstag == -1
      modecolor = DEFAULT_OFF_COLOR;
      mode = 'Show Epoch';
  else
      modecolor = DEFAULT_ON_COLOR;
      mode = 'Hide Epoch';
  end

  u(28) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], ...
    'Tag', 'Display', 'BackgroundColor', modecolor, ...
    'string', mode, 'Callback', displayep);
  y = y - h - tgap * 2;

  % Normalize
  u(21) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin y halfW h], ...
    'Tag', 'Norm', 'string', 'Norm', 'callback', {@normalize_chan,figh});

  % Stack/Spread
  cb_envelope = ['g = get(gcbf,''userdata'');' ...
      'hmenu = findobj(gcf, ''Tag'', ''Envelope_menu'');' ...
      'g.envelope = ~g.envelope;' ...
      'set(gcbf,''userdata'',g);' ...
      'set(gcbo,''string'',fastif(g.envelope,''Spread'',''Stack''));' ...
      'set(hmenu, ''Label'', fastif(g.envelope,''Spread channels'',''Stack channels''));' ...
      'eegplot_adv(''drawp'',0);clear g;'];

  u(22) = uicontrol('Parent', panels.marksTab, 'Units', 'normalized', ...
    'Position', [margin+halfW+gap y halfW h], ...
    'Tag', 'Envelope', 'string', 'Stack', 'callback', cb_envelope);

  %% ========================================================================
  %  METHODS TAB - stacked vertically
  %  ========================================================================

  %% Channel rejection callbacks
  chaninterp  = ['EEG.myVariables{1} = get(findobj(gcf, ''Tag'', ''Channel''),''string'');'];
  plotdiffcom = ['EEG.myVariables{2} = get(findobj(gcf, ''Tag'', ''datadiff''),''Value'');'];
  chaninterp2 = ['EEG.myVariables{3} = get(findobj(gcf, ''Tag'', ''Removal''),''string'');'];

  %% TBT part modified from pop_TBT() scripts
  if isstruct(EEG)
      QuickLabDefs;

      g.eegmethods = ['ICA|', ...
          'BSS EMG (AAR)|', ...
          'Re-reference|', ...
          'Re-epoch|', ...
          'DipFit (par)|', ...
          'Any Script'];

      g.eegoptions = { ...
          ['[], ''' ICATYPE ''' , 0'], ...
          ['components, icatype, display'], ...
          'quick_pca'; ...
          ...
          [''], ...
          'window, windowshift', ...
          'quick_bss2'; ...
          ...
          [' "AVG" '], ...
          'choose reference(s)', ...
          'quick_reref'; ...
          ...
          '0.600,2.648', ...
          'time 1, time 2', ...
          'quick_epoch'; ...
          ...
          ['[],1'], ...
          '[components], dipoles', ...
          'quick_dipfit'; ...
          ...
          [''], ...
          'run any script', ...
          ''; ...
          };

      g.iclmethods = ['All but Brain and Other|', ...
          'Brain|', ...
          'Muscle|', ...
          'Eye|', ...
          'Heart|', ...
          'Line noise|', ...
          'Channel noise|', ...
          'Other'];

      g.icloptions = { ...
          [' .8 1 '], ['min max'], ''; ...
          [' .3 0 '], ['min max'], ''; ...
          [' .8 1 '], ['min max'], ''; ...
          [' .8 1 '], ['min max'], ''; ...
          [' .8 1 '], ['min max'], ''; ...
          [' .8 1 '], ['min max'], ''; ...
          [' .8 1 '], ['min max'], ''; ...
          [' .8 1 '], ['min max'], ''; ...
          };

      g.tbtmethods = ['Abnormal values|', ...
          'Abnormal trends|', ...
          'Improbable data|', ...
          'Abnormal distributions|', ...
          'Abnormal spectra|', ...
          'Max-Min Threshold|', ...
          'Detect Flatline (cleanline)|', ...
          'Detect Channel Pops (by Ugo)'];

      g.tbtoptions = { ...
          ['[1:57,59,60],-150 , 150 ,' num2str(EEG.xmin) ' , ' num2str(EEG.xmax)], ...
          'chans,low/up thresh, starttime, endtime', ...
          'pop_eegthresh'; ...
          ...
          ['[1:57,59,60],' num2str(EEG.pnts) ' , 0.5 , 0.3'], ...
          'chans,winsize, maxslope, minR', ...
          'pop_rejtrend'; ...
          ...
          '[1:57,59,60],3 , 3', ...
          'chans,locthresh, globthresh', ...
          'pop_jointprob'; ...
          ...
          '[1:57,59,60],3 , 3', ...
          'chans,locthresh, globthresh', ...
          'pop_rejkurt'; ...
          ...
          ['[1:57,59,60],''method'' , ''FFT'' , ''threshold'' , [-70 , 15] ,''freqlimits'' , [20 , 55]'], ...
          'chans,th in Db, limits in Hz >34', ...
          'pop_rejspec'; ...
          ...
          ['[1:57,59,60],[1:' num2str(EEG.nbchan) '],[' num2str([EEG.xmin EEG.xmax]*1000) '],100,' num2str([EEG.xmax - EEG.xmin]*1000) ',1,0'], ...
          'chans,chRange,timeRange,minmaxThresh,winSize,stepSize,maW', ...
          'pop_eegmaxmin'; ...
          ...
          ['[1:57,59,60],5, 20'], ...
          ['chans,fl duration, max jitter'], ...
          ''; ...
          ...
          ['[1:57,59,60],{5, 8, 100, 2, [],''mean''}'], ...
          ['chans,SumWindow, StdRej, max rej win, Chancomps, type'], ...
          ''; ...
          };
  else
      g.tbtmethods = {'0','0'};
      g.tbtoptions = {'0','0'};
  end

  g.plotmethods = ['Plot Spectra|', ...
      'Plot IClabel|', ...
      'Plot Component ERPs'];

  g.plotoptions = { ...
      ['40, 2, []'], ['lowpass, highpass, reference'], ''; ...
      ['[]'], 'components, lowpass, highpass', ''; ...
      ['{2,[],[]}'], 'type, reference, project to channel', ''; ...
      };

  g.allmethods = ['TBT|', ...
      'QUICKLAB|', ...
      'ICLABEL|', ...
      'QUICKLAB PLOTS'];

  g.currentoptions = g.tbtoptions;

  y = 0.94;

  % Library tag
  u(25) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'ListTag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', 'Select Library of Functions');
  y = y - hval - tgap;

  % Library popup
  u(32) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'popupmenu', 'HorizontalAlignment', 'center', 'FontSize', 10, ...
    'Tag', 'ListPopup', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, ...
    'string', g.allmethods, 'callback', @change_list, ...
    'TooltipString', 'Select a library of functions');
  y = y - hval - tgap * 2;

  % Method popup
  u(33) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'popupmenu', ...
    'Tag', 'ALLmethods', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, ...
    'string', g.tbtmethods, 'callback', @change_options, ...
    'TooltipString', 'Select a function of the chosen library');
  y = y - hval - tgap * 2;

  % Options edit
  u(34) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'edit', ...
    'Tag', 'ALLoptions', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, ...
    'string', g.tbtoptions{1}, ...
    'TooltipString', 'Options for the selected function');
  y = y - hval - tgap;

  % Hints text
  u(35) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y tw 0.06], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'ALLhints', 'BackgroundColor', DEFAULT_FIG_COLOR, ...
    'string', g.tbtoptions{1,2}, ...
    'TooltipString', ['Hints for the function options,', newline, g.tbtoptions{1,2}]);
  y = y - 0.06 - tgap * 2;

  % Trial% tag  |  Chan# tag
  u(36) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y halfW h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'TBT%tag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '% Trials 4 rej.', ...
    'TooltipString', 'Minimal percentage of trials necessary for a channel to be selected for rejection');

  u(37) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin+halfW+gap y halfW h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'TBTnchanstag', 'BackgroundColor', DEFAULT_FIG_COLOR, 'string', '# Chans 4 rej.', ...
    'TooltipString', 'Minimal number of channels necessary for a trial to be selected for rejection');
  y = y - hval - tgap;

  % Trial% edit  |  Chan# edit
  u(38) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y halfW hval], 'Style', 'edit', ...
    'Tag', 'TBT%', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, 'string', '60');

  u(39) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin+halfW+gap y halfW hval], 'Style', 'edit', ...
    'Tag', 'TBTnchans', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, 'string', '1');
  y = y - hval - tgap * 2;

  % Run button  |  Clear marks button
  u(40) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin y halfW h], ...
    'Tag', 'TBT', 'BackgroundColor', DEFAULT_OFF_COLOR, 'string', 'Run', ...
    'Callback', 'eegplot_adv(''METHODS'');');

  u(41) = uicontrol('Parent', panels.methodsTab, 'Units', 'normalized', ...
    'Position', [margin+halfW+gap y halfW h], ...
    'Tag', 'ClearMarks', 'BackgroundColor', DEFAULT_OFF_COLOR, 'string', 'Clear Marks', ...
    'Callback', ['eegplot_adv(''ClearMarks'');']);

  %% ========================================================================
  %  ACTIONS TAB - stacked vertically
  %  ========================================================================
  y = 0.94;

  % Apply Changes button
  u(60) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
    'Position', [margin y tw 0.06], ...
    'Tag', 'APPLY', 'BackgroundColor', DEFAULT_OFF_COLOR, 'string', 'Apply Changes', ...
    'Callback', ['eegplot_adv(''APPLY'');']);
  y = y - 0.06 - tgap * 3;

  % Transfer to EEGLAB button
  if isempty(g.command)
      tmpcom = 'fprintf(''Rejections saved in variable TMPREJ\n'');';
  else
      tmpcom = g.command;
  end

  closecommand = ['g = get(gcbf,''userdata''); EEG = g.EEG; if g.children, delete(g.children); end' ...
                  'delete(gcbf);' ...
                  'eval(get(findobj(''tag'',''LoadDir''),''Callback''));' ...
                  'eval(get(findobj(''tag'',''LoadFileList''),''Callback''));'];

  acceptcommand = ['g = get(gcbf, ''userdata'');' ...
                   'TMPREJ = g.winrej;' ...
                   'if isfield(g, ''eloc_file'') && isfield(g.eloc_file, ''badchan''); ' ...
                        'TMPREJCHN = find([g.eloc_file.badchan]); ' ...
                   'else TMPREJCHN = [];' ...
                   'end ' ...
                   closecommand ...
                   tmpcom ...
                   '; clear g;'];

  if isempty(g.command)
      tmpsavecom = 'fprintf(''Rejections saved in variable TMPREJ\n'');';
  else
      if g.EEG.plotchannels == 1
          tmpsavecom = g.savecommand;
      else
          tmpsavecom = g.savecommand2;
      end
  end

  savecommand = ['g = get(gcbf, ''userdata'');' ...
                 'TMPEEG = g.EEG;' ...
                 'TMPREJ = g.winrej;' ...
                 'if isfield(g, ''eloc_file'') && isfield(g.eloc_file, ''badchan''); ' ...
                      'TMPREJCHN = find([g.eloc_file.badchan]); ' ...
                 'else TMPREJCHN = [];' ...
                 'end; ' ...
                 tmpsavecom];

  acceptandsavecommand = [savecommand acceptcommand];

  if ~isempty(g.savecommand)
      u(42) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
        'Position', [margin y tw 0.06], ...
        'Tag', 'SaveButton', 'BackgroundColor', [.5 1 0.5], 'string', 'Transfer to EEGLAB', ...
        'Callback', savecommand);
      y = y - 0.06 - tgap * 3;
  end

  % Save text tag
  u(59) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
    'Position', [margin y tw h], 'Style', 'text', 'FontSize', 8, ...
    'Tag', 'save_file_title', 'BackgroundColor', DEFAULT_FIG_COLOR, ...
    'string', 'Enter Text to Add to Filename');
  y = y - hval - tgap;

  % Save text edit
  u(50) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'edit', ...
    'Tag', 'SaveNowText', 'BackgroundColor', DEFAULT_PLOT_BACKGROUND, 'string', '');
  y = y - hval - tgap;

  % Save button
  u(58) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
    'Position', [margin y tw hval], 'Style', 'pushbutton', ...
    'Tag', 'SaveNowButton', 'string', 'Save File with Text', ...
    'callback', ['eegplot_adv(''SAVE'');']);
  y = y - hval - tgap * 3;

  % FFT button  |  ICLabel button
  u(54) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
    'Position', [margin y halfW h], 'Style', 'pushbutton', ...
    'Tag', 'plotFFT', 'string', 'FFT(avg)', ...
    'callback', ['g = get(gcf,''UserData''); quick_spectra(g.EEG,40,2,''AVG'');']);

  ICLcommand = ['g = get(gcf,''UserData''); [EEG,com] = quick_IClabel(g.EEG,[],[],[],[],[''eegplot_adv(''''MERGE_REJECTION'''');'']);'];

  u(55) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
    'Position', [margin+halfW+gap y halfW h], 'Style', 'pushbutton', ...
    'Tag', 'plotICLABEL', 'string', 'IClabel', 'callback', ICLcommand);
  y = y - h - tgap * 2;

  % Events button (if events exist)
  if ~isempty(g.events)
      u(17) = uicontrol('Parent', panels.actionsTab, 'Units', 'normalized', ...
        'Position', [margin y tw h], ...
        'string', 'Events', 'callback', 'eegplot_adv(''drawlegend'', gcbf);');
  end

  %% Set Units to Normalized for all controls (Matlab 2014b compatibility)
  for i = 1:length(u)
      if isprop(eval(['u(' num2str(i) ')']),'Style')
          set(u(i), 'Units', 'Normalized');
      end
  end

  g.scripts = ['BSS|', ...
      'ICA|', ...
      'Reference|', ...
      'Epoch|', ...
      'Channel Reduction'];

  % %%%%%%%%%%%%%%%%%%%%%%%%%%%
  % Set up uimenus
  % %%%%%%%%%%%%%%%%%%%%%%%%%%%

  % Figure Menu %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  m(7) = uimenu('Parent',figh,'Label','Figure');
  m(8) = uimenu('Parent',m(7),'Label','Print');
  uimenu('Parent',m(7),'Label','Edit figure', 'Callback', 'eegplot_adv(''noui'');');
  uimenu('Parent',m(7),'Label','Accept and close','Tag','AcceptAndSave', 'Callback', acceptandsavecommand );
  uimenu('Parent',m(7),'Label','Cancel and close', 'Callback','delete(gcbf)')

  % Portrait %%%%%%%%

  timestring = ['[OBJ1,FIG1] = gcbo;',...
	        'PANT1 = get(OBJ1,''parent'');',...
	        'OBJ2 = findobj(''tag'',''orient'',''parent'',PANT1);',...
		'set(OBJ2,''checked'',''off'');',...
		'set(OBJ1,''checked'',''on'');',...
		'set(FIG1,''PaperOrientation'',''portrait'');',...
		'clear OBJ1 FIG1 OBJ2 PANT1;'];

  uimenu('Parent',m(8),'Label','Portrait','checked',...
      'on','tag','orient','callback',timestring)

  % Landscape %%%%%%%
  timestring = ['[OBJ1,FIG1] = gcbo;',...
	        'PANT1 = get(OBJ1,''parent'');',...
	        'OBJ2 = findobj(''tag'',''orient'',''parent'',PANT1);',...
		'set(OBJ2,''checked'',''off'');',...
		'set(OBJ1,''checked'',''on'');',...
		'set(FIG1,''PaperOrientation'',''landscape'');',...
		'clear OBJ1 FIG1 OBJ2 PANT1;'];

  uimenu('Parent',m(8),'Label','Landscape','checked',...
      'off','tag','orient','callback',timestring)

  % Print command %%%%%%%
  uimenu('Parent',m(8),'Label','Print','tag','printcommand','callback',...
  		['RESULT = inputdlg2( { ''Command:'' }, ''Print'', 1,  { ''print -r72'' });' ...
		 'if size( RESULT,1 ) ~= 0' ...
		 '  eval ( RESULT{1} );' ...
		 'end;' ...
		 'clear RESULT;' ]);

  % Display Menu %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  m(1) = uimenu('Parent',figh,...
      'Label','Display', 'tag', 'displaymenu');

  % window grid %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  m(11) = uimenu('Parent',m(1),'Label','Data select/mark', 'tag', 'displaywin', ...
            'userdata', { 1, [0.8 1 0.8], 0, fastif( g.trialstag(1) == -1, 0, 1)});

          uimenu('Parent',m(11),'Label','Hide marks','Callback', ...
  	        ['g = get(gcbf, ''userdata'');' ...
            'if ~g.winstatus' ...
            '  set(gcbo, ''label'', ''Hide marks'');' ...
            'else' ...
            '  set(gcbo, ''label'', ''Show marks'');' ...
            'end;' ...
            'g.winstatus = ~g.winstatus;' ...
            'set(gcbf, ''userdata'', g);' ...
            'eegplot_adv(''drawb''); clear g;'] )

	% color %%%%%%%%%%%%%%%%%%%%%%%%%%
    if isunix
        uimenu('Parent',m(11),'Label','Choose color', 'Callback', ...
               [ 'g = get(gcbf, ''userdata'');' ...
                 'g.wincolor = uisetcolor(g.wincolor);' ...
                 'set(gcbf, ''userdata'', g ); ' ...
                 'clear g;'] )
    end

  % plot durations
  if g.ploteventdur && isfield(g.events, 'duration')
      disp(['Use menu "Display > Hide event duration" to hide colored regions ' ...
           'representing event duration']);
  end
  if isfield(g.events, 'duration')
      uimenu('Parent',m(1),'Label',fastif(g.ploteventdur, 'Hide event duration', 'Plot event duration'),'Callback', ...
             ['g = get(gcbf, ''userdata'');' ...
              'if ~g.ploteventdur' ...
              '  set(gcbo, ''label'', ''Hide event duration'');' ...
              'else' ...
              '  set(gcbo, ''label'', ''Show event duration'');' ...
              'end;' ...
              'g.ploteventdur = ~g.ploteventdur;' ...
              'set(gcbf, ''userdata'', g);' ...
              'eegplot_adv(''drawb''); clear g;'] )
  end

  % X grid %%%%%%%%%%%%
  m(3) = uimenu('Parent',m(1),'Label','Grid');
  timestring = ['FIGH = gcbf;',...
	            'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
	            'if size(get(AXESH,''xgrid''),2) == 2' ...
		        '  set(AXESH,''xgrid'',''off'');',...
		        '  set(gcbo,''label'',''X grid on'');',...
		        'else' ...
		        '  set(AXESH,''xgrid'',''on'');',...
		        '  set(gcbo,''label'',''X grid off'');',...
		        'end;' ...
		        'clear FIGH AXESH;' ];
  uimenu('Parent',m(3),'Label',fastif(strcmp(g.xgrid, 'off'), ...
         'X grid on','X grid off'), 'Callback',timestring)

  % Y grid %%%%%%%%%%%%%
  timestring = ['FIGH = gcbf;',...
	            'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
	            'if size(get(AXESH,''ygrid''),2) == 2' ...
		        '  set(AXESH,''ygrid'',''off'');',...
		        '  set(gcbo,''label'',''Y grid on'');',...
		        'else' ...
		        '  set(AXESH,''ygrid'',''on'');',...
		        '  set(gcbo,''label'',''Y grid off'');',...
		        'end;' ...
		        'clear FIGH AXESH;' ];
  uimenu('Parent',m(3),'Label',fastif(strcmp(g.ygrid, 'off'), ...
         'Y grid on','Y grid off'), 'Callback',timestring)

  % Grid Style %%%%%%%%%
  m(5) = uimenu('Parent',m(3),'Label','Grid Style');
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'',''--'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','- -','Callback',timestring)
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'',''-.'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','_ .','Callback',timestring)
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'','':'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','. .','Callback',timestring)
  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'set(AXESH,''gridlinestyle'',''-'');',...
		'clear FIGH AXESH;'];
  uimenu('Parent',m(5),'Label','__','Callback',timestring)

  % Submean menu %%%%%%%%%%%%%
  cb =       ['g = get(gcbf, ''userdata'');' ...
              'if strcmpi(g.submean, ''on''),' ...
              '  set(gcbo, ''label'', ''Remove DC offset'');' ...
              '  g.submean =''off'';' ...
              'else' ...
              '  set(gcbo, ''label'', ''Do not remove DC offset'');' ...
              '  g.submean =''on'';' ...
              'end;' ...
              'set(gcbf, ''userdata'', g);' ...
              'eegplot_adv(''drawp'', 0); clear g;'];
  uimenu('Parent',m(1),'Label',fastif(strcmp(g.submean, 'on'), ...
         'Do not remove DC offset','Remove DC offset'), 'Callback',cb)

  % Scale Eye %%%%%%%%%
  timestring = ['[OBJ1,FIG1] = gcbo;',...
	        'eegplot_adv(''scaleeye'',OBJ1,FIG1);',...
		'clear OBJ1 FIG1;'];
  m(7) = uimenu('Parent',m(1),'Label','Show scale','Callback',timestring);

  % Title %%%%%%%%%%%%
  uimenu('Parent',m(1),'Label','Title','Callback','eegplot_adv(''title'')')

  % Stack/Spread %%%%%%%%%%%%%%%
  cb =       ['g = get(gcbf, ''userdata'');' ...
              'hbutton = findobj(gcf, ''Tag'', ''Envelope'');' ...
              'if g.envelope == 0,' ...
              '  set(gcbo, ''label'', ''Spread channels'');' ...
              '  g.envelope = 1;' ...
              '  set(hbutton, ''String'', ''Spread'');' ...
              'else' ...
              '  set(gcbo, ''label'', ''Stack channels'');' ...
              '  g.envelope = 0;' ...
              '  set(hbutton, ''String'', ''Stack'');' ...
              'end;' ...
              'set(gcbf, ''userdata'', g);' ...
              'eegplot_adv(''drawp'', 0); clear g;'];
  uimenu('Parent',m(1),'Label',fastif(g.envelope == 0, ...
         'Stack channels','Spread channels'), 'Callback',cb, 'Tag', 'Envelope_menu')

  % Normalize/denormalize %%%%%%%%%%%%%%%
  uimenu('Parent',m(1),'Label',fastif(g.envelope == 0, ...
         'Normalize channels','Denormalize channels'), 'Callback', {@normalize_chan,figh}, 'Tag', 'Normalize_menu')

  % Settings Menu %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  m(2) = uimenu('Parent',figh,...
      'Label','Settings');

  % Window %%%%%%%%%%%%
  uimenu('Parent',m(2),'Label','Time range to display',...
      'Callback','eegplot_adv(''window'')')

  % Electrode window %%%%%%%%
  uimenu('Parent',m(2),'Label','Number of channels to display',...
      'Callback','eegplot_adv(''winelec'')')

  % Electrodes %%%%%%%%
  m(6) = uimenu('Parent',m(2),'Label','Channel labels');

  timestring = ['FIGH = gcbf;',...
	        'AXESH = findobj(''tag'',''eegaxis'',''parent'',FIGH);',...
		'YTICK = get(AXESH,''YTick'');',...
		'YTICK = length(YTICK);',...
		'set(AXESH,''YTickLabel'',flipud(char(num2str((1:YTICK-1)''),'' '')));',...
		'clear FIGH AXESH YTICK;'];
  uimenu('Parent',m(6),'Label','Show number','Callback',timestring)
  uimenu('Parent',m(6),'Label','Load .loc(s) file',...
      'Callback','eegplot_adv(''loadelect'');')

  uimenu('Parent',m(2),'Label', 'Help', 'callback', 'pophelp(''eegplot_adv'');');

  % Events %%%%%%%%
  ev = uimenu('Parent',m(2),'Label','Events');
  comeventmaxstring   = [ 'tmpg = get(gcbf, ''userdata'');' ...
                'tmpg.plotevent = ''on'';' ...
                'set(gcbf, ''userdata'', tmpg); clear tmpg; eegplot_adv(''emaxstring'');'];
  comeventleg  = [ 'eegplot_adv(''drawlegend'', gcbf);'];

  uimenu('Parent',ev,'Label','Events on'    , 'callback', {@draw_data,figh,0,[],[],ax1,'g.plotevent = ''on'';'},  'enable', fastif(isempty(g.events), 'off', 'on'));
  uimenu('Parent',ev,'Label','Events off'   , 'callback', {@draw_data,figh,0,[],[],ax1,'g.plotevent = ''off'';'}, 'enable', fastif(isempty(g.events), 'off', 'on'));
  uimenu('Parent',ev,'Label','Events'' string length'   , 'callback', comeventmaxstring, 'enable', fastif(isempty(g.events), 'off', 'on'));
  uimenu('Parent',ev,'Label','Events'' legend', 'callback', comeventleg , 'enable', fastif(isempty(g.allevents), 'off', 'on'));

  % %%%%%%%%%%%%%%%%%
  % Set up autoselect
  %%%%%%%%%%%%%%%%%%%

  mouse_motion_com = {'@eegplot_adv,''mouse_motion'';'};

  if ~isempty(g.ctrlselectcommand{1}) || ~isempty(g.ctrlselectcommand{3}) || ...
         ~isempty(g.selectcommand{1}) || ~isempty(g.selectcommand{3})
      g.commandselect{1} = [ 'if strcmp(get(gcbf, ''SelectionType''),''alt''),' ...
           g.ctrlselectcommand{1} '; else ' g.selectcommand{1} '; end;' ];
      g.commandselect{3} = [ 'if strcmp(get(gcbf, ''SelectionType''),''alt''),' ...
           g.ctrlselectcommand{3} '; else ' g.selectcommand{3} '; end;' ];
      set(figh, 'WindowButtonDownFcn',   g.commandselect{1});
      set(figh, 'WindowButtonupFcn',     g.commandselect{3});
  else
      set(figh, 'WindowButtonDownFcn',   {@mouse_down,figh});
      set(figh, 'WindowButtonupFcn',     {@mouse_up,figh});
  end

  set(figh, 'WindowScrollWheelFcn',  {@mouse_scroll_wheel,figh,ax0,ax1,u(10),u(11),u(9)});
  set(figh, 'WindowButtonMotionFcn', {@mouse_motion,figh,ax0,ax1,u(10),u(11),u(9)});
  set(figh, 'WindowKeyPressFcn',     {@eegplot_readkey,figh,ax0,ax1,u(10),u(11),u(9)});
  set(figh, 'interruptible', 'on');

end % end of eegplot_create_ui

%% Local subfunctions (copied from eegplot_adv.m to maintain accessibility)

function tmprank2 = getrank(tmpdata)

tmprank = rank(tmpdata);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Here: alternate computation of the rank by Sven Hoffman
covarianceMatrix = cov(tmpdata', 1);
[~, D] = eig (covarianceMatrix);
rankTolerance = 1e-7;
tmprank2=sum (diag (D) > rankTolerance);
if tmprank ~= tmprank2
    tmprank2 = min(tmprank, tmprank2);
end

function load_directory(EEG,fig)

if isstruct(EEG)
    findex = [1];
    try cd(EEG.filepath);
    catch
    end
    files = dir('*.set');
    findex = find(strcmp({files.name}, EEG.filename));
    set(findobj(fig,'tag','FolderList'),'string',{files(1:end).name},'value',find(strcmp({files.name}, EEG.filename)));
end
